CREATE TABLE IF NOT EXISTS [DEED_CLEAN_TABLE]
  SELECT
    concat_ws(' ',
      property_house_number_prefix,
      property_house_number,
      property_house_number_2,
      property_house_number_suffix,
      property_direction,
      property_street_name,
      property_mode,
      property_quadrant) Property_Address,
    property_city,
    property_state,
    left(property_zipcode, 5) property_zip,
    if(length(property_zipcode)=9, right(property_zipcode,4), '') AS property_zip_plus4,
    latitude,
    longitude,
    absentee_indicator_code,
    owner_corporate_indicator_flag,
    concat_ws(' ', owner_1_first_name_mi, owner_1_last_name) AS owner_1_label_name,
    concat_ws(' ', owner_2_first_name_mi, owner_2_last_name) AS owner_2_label_name,
    owner_1_last_name,
    owner_1_first_name_mi,
    owner_2_last_name,
    owner_2_first_name_mi,
    owner_relationship_type_code,
    concat_ws(' ',
      mail_house_number_prefix,
      mail_house_number,
      mail_house_number_2,
      mail_direction,
      mail_house_number_suffix,
      mail_street_name,
      mail_mode,
      mail_quadrant) Mail_Address,
    mail_apartment_unit_number,
    mail_city,
    mail_state,
    mail_zipcode,
    assd_total_value,
    assd_land_value,
    assd_improvement_value,
    appr_total_value,
    appr_land_value,
    appr_improvement_value,
    mkt_total_value,
    mkt_land_value,
    mkt_improvement_value,
    tax_amount,
    tax_year,
    assessed_year,
    recording_date,
    sale_amount,
    -- sale_date,
    STR_TO_DATE(sale_date, '%Y%m%d') sale_date,
    sale_code,
    inter_family,
    sales_transaction_type_code,
    seller_name_1,
    seller_name_2,
    seller_last_name,
    seller_first_name,
    1st_mortgage_amount,
    1st_mortgage_loan_type_code,
    1st_mortgage_deed_type_code,
    -- 1st_mortgage_date,
    STR_TO_DATE(1st_mortgage_date, '%Y%m%d') 1st_mortgage_date,
    prior_sale_transaction_type_code,
    prior_sale_amount,
    -- prior_sale_date,
    STR_TO_DATE(prior_sale_date, '%Y%m%d') prior_sale_date,
    prior_sale_code,
    -- prior_sale_recording_date,
    STR_TO_DATE(prior_sale_recording_date, '%Y%m%d') prior_sale_recording_date,
    prior_sale_mortgage_amount,
    prior_sale_document_type_code,
    prior_batch_seq,
    prior_batch_id,
    acres,
    land_square_footage,
    universal_building_square_feet,
    universal_building_square_feet_indicator_code,
    building_square_feet,
    garage_parking_square_feet,
    garage_code,
    year_built,
    effective_year_built,
    view,
    pool_code,
    pool_flag,
    parking_type_code,
    parking_spaces,
    roof_type_code,
    roof_cover_code,
    quality_code,
    total_baths,
    frame_code,
    foundation_code,
    floor_code,
    fireplace_type_code,
    fireplace_number,
    fireplace_indicator_flag,
    finished_basement_area,
    exterior_walls_code,
    construction_type_code,
    condition_code,
    bldg_improvement_code,
    bldg_code,
    basement_finish_code,
    stories_number,
    stories_code,
    heating_code,
    unfinished_basement_area,
    units_number,
    seller_carryback,
    private_party_lender,
    pri_cat_code,
    mtg_sec_cat_codes,
    deed_sec_cat_codes,
    cltv,
    input_fips_code,
    input_parcel_id,
    property_match_code,
    exception_code
  FROM [DEED_TABLE];